# Change these first
owner: DigitalIDSystem # Your GitHub organization or username, where this repository lives
repo: regulator-status # The name of this repository

sites:
  - name: Accredited Entities Register
    url: https://accreditation.register.digitalidsystem.gov.au/
    type: globalping
    location: australia
  - name: Australian Government Digital ID System Register
    url: https://agdis.register.digitalidsystem.gov.au/
    type: globalping
    location: australia
  - name: Management API
    url: https://manage.api.digitalidsystem.gov.au/v1/health
    type: globalping
    location: australia
  - name: Accredited Entities Register API
    url: https://register.api.digitalidsystem.gov.au/accredited-entities/v1/health
    type: globalping
    location: australia
  - name: Australian Government Digital ID System Register API
    url: https://register.api.digitalidsystem.gov.au/agdis/v1/health
    type: globalping
    location: australia

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.digitalidsystem.gov.au
  # baseUrl: /your-repo-name
  logoUrl: https://www.digitalidsystem.gov.au/themes/custom/annexbase10/img/AGDIS_RGB_Logo_Colour.svg
  name: Status
  introTitle: "Digital ID Regulator Status"
  theme: light
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  locale: en-AU
